# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
randnums= np.random.randint(1,101,5)
randnums

array([75, 21, 50, 99, 16])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [6]:
import numpy as np
temp = np.zeros((8,8),dtype=int)
temp[1::2,::2] = 1
temp[::2,1::2] = 1
print(temp)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [7]:
import numpy as np
temp = np.random.random((5,5))
tempmax, tempmin = temp.max(), temp.min()
temp = (temp - tempmin)/(tempmax - tempmin)
print(temp)

[[0.26858981 0.44142268 0.03400414 0.86005871 0.14538676]
 [0.91983566 0.95485729 0.03639252 0.03158586 0.        ]
 [0.227961   0.49761636 0.25570454 0.90157161 0.88308705]
 [0.28588958 0.21583799 0.96357954 1.         0.70498627]
 [0.58560446 0.78969788 0.40514562 0.73812472 0.20646782]]


# 5.  How to find common values between two arrays?

In [8]:
import numpy as np
temp1 = np.random.randint(0,10,10)
temp2 = np.random.randint(0,10,10)
print(np.intersect1d(temp1,temp2))

[0 5 6 8]


# 6.How to get the dates of yesterday, today and tomorrow?

In [12]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print('Yesterday',yesterday)
print('Today',today)
print('Tomorrow',tomorrow)


Yesterday 2020-07-25
Today 2020-07-26
Tomorrow 2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [13]:
import numpy as np

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

EQ = np.allclose(A,B)
print(EQ)

EQ = np.array_equal(A,B)
print(EQ)

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [14]:
import numpy as np
temp = np.random.random(10)
temp[temp.argmax()] = 0
print(temp)

[0.05949117 0.46226931 0.19090749 0.         0.05661808 0.42340718
 0.58242625 0.21198788 0.4261395  0.16791737]


# 9. How to print all the values of an array?

In [19]:
import numpy as np
temp = np.zeros((4,4))
print(temp)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [22]:
temp = np.random.rand(5, 10)


temp1 = temp - temp.mean(axis=1, keepdims=True)

print(temp1)

[[ 0.38205464 -0.016293   -0.09450169 -0.43679894 -0.47527979  0.01791926
   0.23580331  0.19558122  0.35695144 -0.16543644]
 [-0.06511539  0.10670874 -0.03166848  0.09116308  0.0524007   0.03626808
  -0.11749778 -0.39873043  0.42980052 -0.10332904]
 [ 0.01740719 -0.37935185 -0.01346203  0.28709     0.0320788   0.24825872
  -0.15163694  0.06322092 -0.28628239  0.1826776 ]
 [ 0.29472713 -0.02260843  0.21002141 -0.27614909  0.42437437 -0.10079514
  -0.00899058 -0.2266434  -0.13605553 -0.15788074]
 [-0.26313946  0.44848422 -0.0495739   0.16186792  0.18147147  0.0176223
  -0.05582557 -0.25992599  0.11384786 -0.29482886]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [24]:
temp = np.ones(10)
temp1 = np.random.randint(0,len(temp1),20)
temp += np.bincount(temp1, minlength=len(temp))
print(Z)
np.add.at(temp, temp1, 1)
print(temp)

[5. 5. 5. 1. 5. 5. 7. 5. 3. 9.]
[ 9.  9. 15.  7.  5.  1.  1.  1.  1.  1.]


# 12.How to get the diagonal of a dot product?

In [25]:
tempA = np.random.uniform(0,1,(5,5))
tempB = np.random.uniform(0,1,(5,5))

np.sum(tempA * tempB.T, axis=1)

array([1.40290519, 0.35324955, 1.71725044, 0.85968882, 1.08679698])

# 13.How to find the most frequent value in an array?

In [26]:
tempZ = np.random.randint(0,10,50)
print(np.bincount(tempZ).argmax())

5


# 14.How to get the n largest values of an array

In [27]:
tempZ = np.arange(10000)
np.random.shuffle(tempZ)
n = 5

print (tempZ[np.argpartition(-tempZ,n)[:n]])

[9996 9998 9997 9999 9995]


# 15.How to create a record array from a regular array?

In [28]:
tempZ = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
tempR = np.core.records.fromarrays(tempZ.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(tempR)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
